sudo: required
services:
  - docker
language: bash
script:
  - docker pull hypriot/qemu-register
  - docker create --name qemu hypriot/qemu-register
  - docker cp qemu:qemu-arm qemu-arm-static
  - echo IMG_NAME='pi-cloud' >config
  - touch ./stage3/SKIP ./stage4/SKIP
  - rm stage4/EXPORT*
  - ./build-docker.sh
branches:
  only:
    - cloud
    - check-qemu
    - /^v\d.*$/
deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_TOKEN}
  file:
    - deploy/image_$(date +%Y-%m-%d)-pi-cloud-lite.zip
  on:
    tags: true
    repo: sealsystems/pi-gen
