sudo: required
services:
  - docker
language: bash
script:
  - ls -l /usr/bin
  - wget https://github.com/multiarch/qemu-user-static/releases/download/v2.8.0/x86_64_qemu-arm-static.tar.gz
  - tar xzvf x86_64_qemu-arm-static.tar.gz -C /usr/bin
  - ls -l /usr/bin
  - echo IMG_NAME='pi-cloud' >config
  - touch ./stage3/SKIP ./stage4/SKIP
  - rm stage4/EXPORT*
  - ./build-docker.sh
branches:
  only:
    - cloud
    - check-qemu
    - /^v\d.*$/
deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_TOKEN}
  file:
    - deploy/image_$(date +%Y-%m-%d)-pi-cloud-lite.zip
  on:
    tags: true
    repo: sealsystems/pi-gen
